import 'package:tour360/models/place.dart';

List<Place> mostSearchedPalces = [
  Place(
      image:
          'https://images.mapsofworld.com/allwonders/pictures-of-taj-mahal-in-agra-3.jpg',
      name: "Taj Mahal, India"),
  Place(
      image:
          'https://cdn.pixabay.com/photo/2018/04/25/09/26/eiffel-tower-3349075_1280.jpg',
      name: "Eiffel Tower, Paris"),
  Place(
      image: 'https://wallpapercave.com/wp/wp3011579.jpg',
      name: "Statue of Liberty, New York"),
  Place(
      image: 'https://live.staticflickr.com/65535/25409191563_836645a7d4_b.jpg',
      name: "Pyramids of Giza, Egypt"),
  Place(
      image:
          'https://cdn.londonandpartners.com/visit/london-organisations/buckingham-palace/100223-640x360-buckingham-palace-dusk-640.jpg',
      name: "Buckingham Palace, London"),
  Place(
      image: 'https://wallpaperaccess.com/full/16255.jpg',
      name: "Mount Fuji, Japan"),
  Place(
      image:
          'https://www.onthegotours.com/repository/Great-Wall-mountains-and-blue-sky--China-Tours--On-The-Go-Tours-279781450457645_crop_610_410.jpg',
      name: "Great Wall of China, China"),
  Place(
      image:
          'https://img.staticmb.com/mbcontent/images/uploads/2022/9/golden-temple_1663763909577.jpg',
      name: "Golden Temple, India"),
];

List<Place> topPlaces = [
  Place(
      image:
          'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/d3/a8/57/images-30-largejpg.jpg',
      name: "Amber Palace"),
  Place(
      image:
          'https://thumbor.bigedition.com/campania-amalfi-coast/IvwTPRd9LyT2Cb-0gARc80z1p7E=/800x599/filters:format(webp):quality(80)/granite-web-prod/e2/03/e2031911537a451cb1b967e421556e22.jpeg',
      name: 'Amalfi Coast, Italy'),
  Place(
      image:
          'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/fa/e0/29/tirumala-temple.jpg?w=500&h=-1&s=1',
      name: 'Tirumala Temple'),
  Place(
      image:
          'https://thumbor.bigedition.com/niagara-falls-in-autumn-canadian-side/xcgqfExKUZGrdfkcWjZvvQUDjes=/800x600/filters:format(webp):quality(80)/granite-web-prod/f2/09/f209109fabdb49d4a3d115acbfe3d5e9.jpeg',
      name: "Niagara Falls"),
  Place(
      image:
          'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/40/ce/df/marine-drive-seen-as.jpg?w=500&h=400&s=1',
      name: 'Marine Drive'),
  Place(
      image:
          'https://thumbor.bigedition.com/white-washed-houses-in-santorini/siyAWn4oCFZice4SyOVDpi7h8gM=/800x600/filters:format(webp):quality(80)/granite-web-prod/c7/db/c7db8df857e14634b45b9d4a89675f08.jpeg',
      name: 'Santorini, Greece'),
  Place(
      image:
          "https://thumbor.bigedition.com/florience-center-italy/ppu87myqAo3O6NiBC8sNGQuqAeI=/800x600/filters:format(webp):quality(80)/granite-web-prod/86/36/8636a929993f4f1c8ef9694eacf66755.jpeg",
      name: "Florence, Italy"),
  Place(
      image:
          'https://thumbor.bigedition.com/dubai-skyscrappers/QvPjfQHSnn2WPgpC49IOTJsQXFs=/800x600/filters:format(webp):quality(80)/granite-web-prod/89/cf/89cf25de2e974fe2a31fa77cd17a10af.jpeg',
      name: "Dubai, United Arab Emirates"),
  Place(
      image:
          'https://www.planetware.com/photos-large/IND/india-top-attractions-amer-fort.jpg',
      name: 'Amer Fort, Jaipur'),
  Place(
      image:
          'https://www.planetware.com/wpimages/2019/08/india-top-attractions-goa-beaches.jpg',
      name: 'The Beaches of Goa'),
  Place(
      image:
          'https://www.planetware.com/photos-large/IND/india-top-attractions-mysore-palace.jpg',
      name: 'Mysore Palace'),
  Place(
      image:
          'https://thumbor.bigedition.com/machu-picchu-peru/4SKq3Gxb_g0JNtnBKPoCad7wpeM=/800x600/filters:format(webp):quality(80)/granite-web-prod/83/eb/83eb5f27cb4f42b2b6f33bb2f54dce95.jpeg',
      name: "Machu Picchu, Peru"),
  Place(
      image:
          'https://thumbor.bigedition.com/landmark-temple-gates-in-bali/Bu5WIHkLYv1ylr5keAUKKG74rXo=/800x600/filters:format(webp):quality(80)/granite-web-prod/65/c6/65c68f64343649e689f4af286963d116.jpeg',
      name: "Bali, Indonesia"),
  Place(
      image:
          'https://thumbor.bigedition.com/sunset-in-the-maldives/kgD-Ypab67Owy8qSESsrGyMWm5M=/800x600/filters:format(webp):quality(80)/granite-web-prod/1f/ea/1feabe852f07412b833f01a9371e54fe.jpeg',
      name: 'Maldives'),
  Place(
      image:
          'https://thumbor.bigedition.com/rocky-beach-in-maui/GIw8tcAQjZi9eGdibbhG__IGY2Q=/800x600/filters:format(webp):quality(80)/granite-web-prod/94/c0/94c0cb990dcd4dbcad7d912e8e550537.jpeg',
      name: 'Maui, Hawaii'),
  Place(
      image:
          'https://www.adotrip.com/public/images/city/5c3f0da84f7ee-Ooty%20Sightseeing.jpg',
      name: 'Ooty, Tamil Nadu'),
  Place(
      image:
          'https://thumbor.bigedition.com/milford-sound/EcV_FeB89dAq7wQ3aCxa4GcuL9o=/800x600/filters:format(webp):quality(80)/granite-web-prod/30/87/3087e29fe86b4f8d94a52fdf529ae805.jpeg',
      name: 'South Island, New Zealand'),
];

List<String> searchList = [
  'Eiffel Tower, Paris',
  'Great Wall of China, China',
  'Colosseum, Rome',
  'Statue of Liberty, New York City',
  'Machu Picchu, Peru',
  'Taj Mahal, Agra',
  'Pyramids of Giza, Egypt',
  'Sydney Opera House, Australia',
  'Christ the Redeemer, Rio de Janeiro',
  'Stonehenge, England',
  'Big Ben, London',
  'Santorini, Greece',
  'Petra, Jordan',
  'Grand Canyon, USA',
  'Angkor Wat, Cambodia',
  'Burj Khalifa, Dubai',
  'Acropolis of Athens, Greece',
  'Niagara Falls, USA/Canada',
  'Kremlin, Moscow',
  'Louvre Museum, Paris',
  'Yellowstone National Park, USA',
  'Galápagos Islands, Ecuador',
  'Alhambra, Spain',
  'Table Mountain, South Africa',
  'Mount Fuji, Japan',
  'Great Barrier Reef, Australia',
  'Buckingham Palace, London',
  'Vatican City, Vatican',
  'Sagrada Familia, Barcelona',
  'Neuschwanstein Castle, Germany',
  'Golden Gate Bridge, San Francisco',
  'Versailles Palace, France',
  'Bora Bora, French Polynesia',
  'Louvre Abu Dhabi, UAE',
  'Petra, Jordan',
  'Hagia Sophia, Istanbul',
  'Machu Picchu, Peru',
  'Great Ocean Road, Australia',
  'Mont Saint-Michel, France',
  'Chichen Itza, Mexico',
  'Galata Tower, Istanbul',
  'The Louvre, Paris',
  'The Blue Mosque, Istanbul',
  'The Matterhorn, Switzerland',
  'The Vatican Museums, Vatican City',
  'The Acropolis, Athens',
  'The Great Sphinx, Giza',
  'The Alhambra, Granada',
  'The Eiffel Tower, Paris',
  'The Forbidden City, Beijing',
  'The Christ the Redeemer, Rio de Janeiro',
  'The Taj Mahal, Agra',
  'The Colosseum, Rome',
  'The Sydney Opera House, Sydney',
  'The Statue of Liberty, New York',
  'The Leaning Tower of Pisa, Italy',
  'The Tower of London, England',
  'The Grand Palace, Bangkok',
  'The Kremlin, Moscow',
  'The Ring of Kerry, Ireland',
  'The Dead Sea, Jordan',
  'The Amazon Rainforest, Brazil',
  'The Serengeti, Tanzania',
  'The Great Wall of China, China',
  'The Blue Lagoon, Iceland',
  'The Northern Lights, Norway',
  'The Cliffs of Moher, Ireland',
  'The Great Smoky Mountains, USA',
  'The Maldives',
  'The Sahara Desert, Africa',
  'The fjords of Norway',
  'The Galapagos Islands, Ecuador',
  'The Amazon River, Brazil',
  'The Great Lakes, USA/Canada',
  'The Serengeti National Park, Tanzania',
  'The Dolomites, Italy',
  'The Scottish Highlands',
  'The Canadian Rockies',
  'The Isle of Skye, Scotland',
  'The Loire Valley, France',
  'The Cinque Terre, Italy',
  'The Amalfi Coast, Italy',
  'The Scottish Highlands',
  'The Danube River, Europe',
  'The Black Forest, Germany',
  'The Rockies, Canada',
  'The Andes, South America',
  'The Himalayas, Asia',
  'The Alps, Europe',
  'The Carpathians, Europe',
  'The Pyrenees, Europe',
  'The Caucasus Mountains, Europe/Asia',
  'The Appalachian Mountains, USA',
  'The Rockies, USA',
  'The Sierra Nevada, USA',
  'The Atlas Mountains, Morocco',
  'The Andes, South America',
  'The Himalayas, Asia',
  'The Alps, Europe',
  'The Pyrenees, Europe',
  'Frank Lloyd Wright',
  'Le Corbusier',
  'Zaha Hadid',
  'I.M. Pei',
  'Ludwig Mies van der Rohe',
  'Frank Gehry',
  'Norman Foster',
  'Tadao Ando',
  'Alvar Aalto',
  'Renzo Piano',
  'Bjarke Ingels',
  'Richard Meier',
  'Louis Kahn',
  'Eero Saarinen',
  'Moshe Safdie',
  'Oscar Niemeyer',
  'Daniel Libeskind',
  'Peter Zumthor',
  'Richard Rogers',
  'Charles Correa',
  'Kengo Kuma',
  'Jean Nouvel',
  'Robert Venturi',
  'Philip Johnson',
  'Santiago Calatrava',
  'Michael Graves',
  'Kenzo Tange',
  'Tadao Ando',
  'Toyo Ito',
  'David Adjaye',
  'Fumihiko Maki',
  'Shigeru Ban',
  'Rafael Moneo',
  'Richard Serra',
  'Moshe Safdie',
  'Peter Eisenman',
  'Daniel Libeskind',
  'Alvaro Siza',
  'Zaha Hadid',
  'Jean Nouvel',
  'Norman Foster',
  'Richard Rogers',
  'Frank Gehry',
  'Renzo Piano',
  'I.M. Pei',
  'Louis Sullivan',
  'Eero Saarinen',
  'Charles Correa',
  'Kengo Kuma',
  'Tadao Ando',
  'Robert A.M. Stern',
  'Michael Graves',
  'Richard Meier',
  'Bjarke Ingels',
  'Fumihiko Maki',
  'Shigeru Ban',
  'Toyo Ito',
  'Rafael Moneo',
  'David Adjaye',
  'Kenzo Tange',
  'Oscar Niemeyer',
  'Louis Kahn',
  'Alvar Aalto',
  'Frank Lloyd Wright',
  'Le Corbusier',
  'Eero Saarinen',
  'Richard Serra',
  'Peter Zumthor',
  'Zaha Hadid',
  'Santiago Calatrava',
  'Norman Foster',
  'Richard Rogers',
  'Frank Gehry',
  'Renzo Piano',
  'I.M. Pei',
  'Louis Sullivan',
  'Michael Graves',
  'Kenzo Tange',
  'Charles Correa',
  'Tadao Ando',
  'Bjarke Ingels',
  'Fumihiko Maki',
  'Shigeru Ban',
  'Toyo Ito',
  'Rafael Moneo',
  'David Adjaye',
  'Richard Meier',
  'Oscar Niemeyer',
  'Louis Kahn',
  'Alvar Aalto',
  'Frank Lloyd Wright',
  'Le Corbusier',
  'Eero Saarinen',
  'Richard Serra',
  'Peter Zumthor',
  'Zaha Hadid',
  'Santiago Calatrava',
  'Norman Foster',
  'Richard Rogers',
  'Frank Gehry',
  'Taj Mahal, Agra',
  'Red Fort, Delhi',
  'Jaipur City, Rajasthan',
  'Varanasi Ghats, Varanasi',
  'Hampi, Karnataka',
  'Kerala Backwaters, Kerala',
  'Golden Temple, Amritsar',
  'Jaisalmer Fort, Rajasthan',
  'Ajanta and Ellora Caves, Maharashtra',
  'Gateway of India, Mumbai',
  'Mysore Palace, Mysore',
  'Udaipur City Palace, Udaipur',
  'Rishikesh, Uttarakhand',
  'Leh-Ladakh',
  'Andaman Islands',
  'Khajuraho Temples, Madhya Pradesh',
  'Sanchi Stupa, Madhya Pradesh',
  'Nainital, Uttarakhand',
  'Coorg, Karnataka',
  'Ooty, Tamil Nadu',
  'Mahabalipuram, Tamil Nadu',
  'Jodhpur, Rajasthan',
  'Ranthambore National Park, Rajasthan',
  'Chichen Itza, Mexico',
  'Bandhavgarh National Park, Madhya Pradesh',
  'Kanyakumari, Tamil Nadu',
  'Rann of Kutch, Gujarat',
  'Kaziranga National Park, Assam',
  'Chhatrapati Shivaji Maharaj Terminus, Mumbai',
  'Victoria Memorial, Kolkata',
  'Qutub Minar, Delhi',
  'Lotus Temple, Delhi',
  'India Gate, Delhi',
  "Humayun's Tomb, Delhi",
  'Chola Temples, Tamil Nadu',
  'Sundarbans National Park, West Bengal',
  'Mahabodhi Temple, Bodh Gaya',
  'Hampi, Karnataka',
  'Khajuraho, Madhya Pradesh',
  'Dudhwa National Park, Uttar Pradesh',
  'Kodaikanal, Tamil Nadu',
  'Gulmarg, Jammu & Kashmir',
  'Pahalgam, Jammu & Kashmir',
  'Shimla, Himachal Pradesh',
  'Manali, Himachal Pradesh',
  'Munnar, Kerala',
  'Wayanad, Kerala',
  'Kanyakumari, Tamil Nadu',
  'Chikmagalur, Karnataka',
  'Coorg, Karnataka',
  'Munnar, Kerala',
  'Rishikesh, Uttarakhand',
  'Haridwar, Uttarakhand',
  'Jim Corbett National Park, Uttarakhand',
  'Sikkim',
  'Ladakh',
  'Dhanaulti, Uttarakhand',
  'Mussoorie, Uttarakhand',
  'Auli, Uttarakhand',
  'Tawang, Arunachal Pradesh',
  'Ziro Valley, Arunachal Pradesh',
  'Shillong, Meghalaya',
  'Kaziranga National Park, Assam',
  'Majuli Island, Assam',
  'Tawang Monastery, Arunachal Pradesh',
  'Loktak Lake, Manipur',
  'Khonoma Village, Nagaland',
  'Naga Hills, Nagaland',
  'Khangchendzonga National Park, Sikkim',
  'Neora Valley National Park, West Bengal',
  'Sundarbans, West Bengal',
  'Bandipur National Park, Karnataka',
  'Nagarhole National Park, Karnataka',
  'Periyar National Park, Kerala',
  'Silent Valley National Park, Kerala',
  'Pench National Park, Madhya Pradesh',
  'Tadoba Andhari Tiger Reserve, Maharashtra',
  'Dudhwa National Park, Uttar Pradesh',
  'Sariska Tiger Reserve, Rajasthan',
  'Ranthambore National Park, Rajasthan',
  'Gir National Park, Gujarat',
  'Kanha National Park, Madhya Pradesh',
  'Bandhavgarh National Park, Madhya Pradesh',
  'Pench National Park, Madhya Pradesh',
  'Simlipal National Park, Odisha',
  'Khangchendzonga National Park, Sikkim',
  'Namdapha National Park, Arunachal Pradesh',
  'Valley of Flowers National Park, Uttarakhand',
  'Great Himalayan National Park, Himachal Pradesh',
  'Nanda Devi National Park, Uttarakhand',
  'Khangchendzonga National Park, Sikkim',
  'Periyar Wildlife Sanctuary, Kerala',
  'Bhadra Wildlife Sanctuary, Karnataka',
  'Nagarhole National Park, Karnataka',
  'Bandipur National Park, Karnataka',
  'Silent Valley National Park, Kerala',
  'Anamudi Peak, Kerala',
  'Agasthyamalai Biosphere Reserve, Kerala',
  'Nilgiri Biosphere Reserve, Tamil Nadu',
  'Western Ghats',
  'Netarhat, Jharkhand',
];
